saskatoon/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/services', 'ServiceController@services')->name('services');
Route::get('/booking', 'IndexController@booking')->name('booking');
Route::get('/faq', 'IndexController@faq')->name('faq');
Route::get('/now-hiring', 'IndexController@nowHiring')->name('now-hiring');
//Route::get('/gallery-commercial', 'IndexController@galleryCommercial')->name('gallery.commercial');
//Route::get('/gallery-residential', 'IndexController@galleryResidential')->name('gallery.residential');
Route::get('/gallery-{commercial}', 'IndexController@Gallery')->name('gallery');
Route::get('/testimonial', 'IndexController@testimonial')->name('testimonial');

Route::get('/service-house-cleaning', 'ServiceController@serviceHouse')->name('service-house-cleaning');
Route::get('/service-office-cleaning', 'ServiceController@serviceOffice')->name('service-office-cleaning');
Route::get('/service-moving-day-cleaning', 'ServiceController@serviceMoving')->name('service-moving-day-cleaning');
Route::get('/service-preparation-for-sale', 'ServiceController@servicePreparation')->name('service-preparation-for-sale');
Route::get('/service-washing-carpet', 'ServiceController@serviceCarpet')->name('service-washing-carpet');
Route::get('/service-washing-windows', 'ServiceController@serviceWindows')->name('service-washing-windows');
Route::get('/service-grand', 'ServiceController@serviceGrand')->name('service-grand');
Route::get('/service-deep-cleaning', 'ServiceController@serviceDeep')->name('service-deep-cleaning');
Route::get('/service-post-construction-clean-up', 'ServiceController@servicePostConstruction')->name('service-post-construction-clean-up');



Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Auth::routes();
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'IndexController@index')->name('admin.index');
    Route::resource('/testimonial', 'TestimonialController', ['as' => 'admin']);
    Route::get('/testimonial/{id}/block', 'TestimonialController@block', ['as' => 'admin'])->name('admin.testimonial.block');
    Route::resource('/faq', 'FaqController', ['as' => 'admin']);
    Route::get('/faq/{id}/block', 'FaqController@block', ['as' => 'admin'])->name('admin.faq.block');

    Route::resource('/gallery', 'AlbumController', ['as' => 'admin']);
    Route::post('/gallery/{id}/position', 'AlbumController@changePosition', ['as' => 'admin'])->name('admin.gallery.position');
    Route::get('gallery/{type}', 'AlbumController@show', ['as' => 'admin'])->name('admin.gallery.search');
    Route::get('/gallery/{id}/block', 'AlbumController@block', ['as' => 'admin'])->name('admin.gallery.block');


    Route::get('/setting', 'IndexController@setting')->name('admin.setting');
    Route::post('/setting', 'IndexController@update')->name('admin.setting.update');

    Route::resource('/client', 'ClientController', ['as' => 'admin']);
    Route::get('/client/{id}/block', 'ClientController@block', ['as' => 'admin'])->name('admin.client.block');


});

saskatoon/resources/views/admin/client.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <main id="clientsAdmin">
        <section class="settingsAdmin_section testimonialsAdmin_section clientAdmin_section">
            @include('admin.navigation')
            <div class="settingAdmin_block">
                <div class="settingAdmin_block_title">
                    <img src="../images/admin/galleryAdmin_big.png" alt="" class="settingAdmin_block_title_icon">
                    <p class="settingAdmin_block_title_text">Clients</p>
                </div>
                <div class="gallery_tabs">
                    <div class="gallery_tabs_addItem">
                        <button data-action="{{route('admin.client.store')}}"
                                class="gallery_tabs_addItem_btn edit_btn addClient">Add New Client
                        </button>
                    </div>
                </div>
                <div class="testimonials_block">

                    <table id="table1" class="testimonials_table active">
                        <tr class="testimonials_table_head">
                            <th class="main_picture">
                                <p>#</p>
                            </th>
                            <th class="main_picture">
                                <p>Client</p>
                            </th>
                            <th class="btn">

                            </th>
                        </tr>
                        @forelse($clients as $key => $client)
                        <tr class="testimonials_table_body">

                                <td>
                                    <p>{{ $key + 1 }}</p>
                                </td>
                                <td class="main_picture">
                                    @isset($client->logo)
                                        <img src=" {{ Storage::disk('upload')->url($client->logo) }}"
                                             class="main_picture_img" alt="">
                                    @endisset
                                </td>


                                <td class="testimonials_table_box">

                                    <div class="testimonials_table_box_btn edit_btn edit_client">
                                        <button data-action="{{route('admin.client.update', $client->id)}}">Edit
                                        </button>
                                    </div>

                                    <form action="{{route('admin.client.block', $client->id)}}" method="GET"
                                          class="testimonials_table_box_btn">
                                        <button type="submit">@if ($client->status) Hide @else Show @endif</button>
                                    </form>

                                    <form action="{{route('admin.client.destroy', $client->id)}}" method="POST"
                                          class="testimonials_table_box_btn delete">
                                        <input type="hidden" name="_method" value="delete">
                                        {{ csrf_field() }}
                                        <button type="submit">Delete</button>
                                    </form>

                                </td>
                        </tr>
                        @empty

                            <td>
                                <h3 style="text-alight:center">Данные отсутствуют</h3>
                            </td>

                        @endforelse

                    </table>
                </div>
                <div class="clientAdmin_modal">
                    <div class="clientAdmin_modal_overlay"></div>
                    <form class="input_box image_box clientAdmin_modal_container"
                          action="{{route('admin.client.store')}}" method="post">
                        @csrf
                        <input class="method" type="hidden" name="_method" value="">
                        <input type="hidden" name="client_id" value="">

                        <p class="edit_modal_container_item_title">Image</p>
                        <div class="tabul_container row">
                            <div class="col-12 image_box">
                                <label class="tabul_container_item main_image">
                                    <input class="tabul_container_item_input" type="file" name="logo">
                                    <img src="" alt="" class="tabul_container_item_image">
                                </label>
                            </div>
                        </div>
                        <button class="clientAdmin_modal_container_btn">Save</button>
                        <img src="http://127.0.0.1:8080/images/admin/close.png" alt="" class="clients_closer">
                    </form>
                </div>
            </div>
        </section>
    </main>

@endsection

saskatoon/resources/views/admin/gallery.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <main id="galleryAdmin">

        <section class="settingsAdmin_section galleryAdmin_section">

            @include('admin.navigation')

            <div class="settingAdmin_block">


                <div class="settingAdmin_block_title">
                    <img src="{{ asset('images/admin/galleryAdmin_big.png') }}" alt=""
                         class="settingAdmin_block_title_icon">
                    <p class="settingAdmin_block_title_text">Gallery</p>
                </div>
                <div class="gallery_tabs">
                    <a href="{{ route('admin.gallery.show', 'residential') }}" class="gallery_tabs_item
                        @if (request()->path() == 'admin/gallery/residential') active @endif ">Residential
                        gallery</a>
                    <a href="{{ route('admin.gallery.show', 'commercial') }}" class="gallery_tabs_item
                            @if (request()->path() == 'admin/gallery/commercial') active @endif ">Commercial
                        gallery</a>
                    <div class="create_gallery gallery_tabs_addItem">
                        <button class="gallery_tabs_addItem_btn"
                                data-action="{{route('admin.gallery.store')}}"> Add New
                        </button>
                    </div>
                    <form action="{{ route('admin.gallery.search', $type) }}" method="GET" class="gallery_tabs_search">
                        <button type="submit" class="gallery_tabs_search_btn"><img
                                    src="{{ asset('images/admin/search_admin.png') }}"
                                    alt="" class="gallery_tabs_search_btn_icon"></button>
                        <input type="text" name="search" class="gallery_tabs_search_input" placeholder="Search">
                    </form>
                </div>


                <div class="testimonials_block">


                    @if($albums->lastPage() > 1)
                        <div class="pagination_table">
                            <div class="pagination_table_counter">
                                <span class="pagination_table_counter_current">{{ $albums->currentPage() }}</span>
                                <span>из</span>
                                <span class="pagination_table_counter_total">{{ $albums->lastPage() }}</span>
                            </div>
                            <div class="pagination_table_arrows">
                                @if($albums->currentPage() !== 1)
                                    <a href="{{ $albums->url(($albums->currentPage() - 1 )) }}"><img
                                                src="{{ asset('images/admin_arrow.svg') }}" alt=""
                                                class="pagination_table_arrows_item prev_arrow"></a>
                                @endif
                                @if($albums->currentPage() !== $albums->lastPage())
                                    <a href="{{ $albums->url(($albums->currentPage() + 1 )) }}"><img
                                                src="{{ asset('images/admin_arrow.svg') }}" alt=""
                                                class="pagination_table_arrows_item next_arrow"></a>
                                @endif
                            </div>
                        </div>
                    @endif
                    <table class="testimonials_table ">
                        <tr class="testimonials_table_head">
                            <th class="album_name">
                                <p>Album Name</p>
                            </th>
                            <th class="">
                                <p>Position</p>
                            </th>
                            <th class="name_table">
                                <p>Place</p>
                            </th>
                            <th class="name_date">
                                <p>Date</p>
                            </th>
                            <th class="main_picture">
                                <p>Main picture</p>
                            </th>
                            <th class="all_pictures">
                                <p>All pictures</p>
                            </th>
                        </tr>

                        @forelse($albums as $key => $album)
                            <tr class="testimonials_table_body">
                                <td class="album_name">
                                    <p>{{ $album->name ?? '' }}</p>
                                </td>

                                <td>
                                    <div class="form-group styled-select">
                                        <select class="gallery_position styled form-control"  id="inputState"
                                                data-action="{{ route('admin.gallery.position', $album->id)  }}"
                                                name="position">
                                            @foreach($albums_all as $key => $item)
                                                <option value="{{$item->position}}"
                                                        @if($item->position == $album->position) selected @endif>{{ $key + 1 }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </td>
                                <td class="name_place">
                                    <p>{{ $album->place ?? '' }}</p>
                                </td>
                                <td class="name_date" data-value="@isset($album->created_at){{ $album->created_at->format('Y-m-d') }}@endisset">
                                    <p>@isset($album->created_at) {{ $album->created_at->format('d.m.Y') }} @endisset</p>
                                </td>
                                <td class="main_picture">
                                    @isset($album->main_photo)
                                        <img src=" {{ Storage::disk('upload')->url($album->main_photo) }}"
                                             class="main_picture_img" alt="">
                                    @endisset
                                </td>
                                <td class="all_pictures">
                                    <div>
                                        @if ($album->photos->count() > 0)
                                            @for ($i = 0; $i < 4; $i++)
                                                @isset($album->photos[$i])
                                                    <img src="{{ Storage::disk('upload')->url($album->photos[$i]->image) }}"
                                                         alt=""
                                                         class="all_pictures_img">
                                                @endisset
                                            @endfor
                                        @endif
                                    </div>
                                    <div class="hidden-galery">
                                        @if ($album->photos->count() > 0)
                                            @foreach ($album->photos as $photo)
                                                    <p src="{{ Storage::disk('upload')->url($photo->image) }}" data-id="{{$photo->id}}"></p>
                                            @endforeach
                                        @endif
                                    </div>
                                </td>

                                <td class="testimonials_table_box">
                                    <div class="edit-gallery testimonials_table_box_btn edit_btn">
                                        <button data-id="{{$album->id}}" data-action="{{route('admin.gallery.update', $album->id)}}">Edit
                                        </button>
                                    </div>
                                    <form action="{{route('admin.gallery.block', $album->id)}}" method="GET"
                                          class="testimonials_table_box_btn">
                                        <button type="submit">@if ($album->status) Hide @else Show @endif</button>
                                    </form>
                                    <form action="{{route('admin.gallery.destroy', $album->id)}}" method="POST"
                                          class="testimonials_table_box_btn delete">
                                        <input type="hidden" name="_method" value="delete">
                                        {{ csrf_field() }}
                                        <button type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td>
                                    <h3 style="text-alight:center">Данные отсутствуют</h3>
                                </td>
                            </tr>
                        @endforelse
                        @if ($errors->any())
                            <tr>
                                @foreach($errors as $error)
                                    <td>
                                        <h3 style="text-alight:center">{{ $error }}</h3>
                                    </td>
                                @endforeach
                            </tr>
                        @endif

                    </table>
                </div>


                <div class="galleryAdmin_modal">
                    <div class="overlay"></div>
                    <div class="galleryAdmin_modal_container">


                        <form enctype="multipart/form-data" id="galleryForm" class="galleryAdmin_modal_container_form"
                              action="{{route('admin.gallery.store')}}" method="post">
                            <input class="method" type="hidden" name="_method" value="">
                            <input class="count" type="hidden" name="count" value="">
                            <input type="hidden" name="type" value="{{ $type ?? '' }}">
                            <input type="hidden" name="album_id" value="">
                            @csrf

                            <div class="galleryAdmin_modal_container_box">
                                <p class="galleryAdmin_modal_container_box_title">Album Name</p>
                                <input type="text" name="name"
                                       class="galleryAdmin_modal_container_box_input album_name">
                            </div>
                            <div class="galleryAdmin_modal_container_box">
                                <p class="galleryAdmin_modal_container_box_title">Place</p>
                                <input type="text" name="place"
                                       class="galleryAdmin_modal_container_box_input place_input">
                            </div>

                            <div class="galleryAdmin_modal_container_box">
                                <p class="galleryAdmin_modal_container_box_title">Date</p>
                                <input name="created_at" id="date" type="date"
                                       class="galleryAdmin_modal_container_box_input date_input"
                                       value="">
                            </div>

                            <div class="relativeBlock">
                                <input type="hidden" name="deleted_images" value="">
                                <div class="tabul active" id="tabul1">
                                    <p class="tabul_text">Main picture</p>
                                    <div class="tabul_container row">
                                        <div class="col-12 col-sm-6 col-lg-4 image_box">
                                            <label class="tabul_container_item main_image">
                                                <input class="tabul_container_item_input" type="file" name="main_photo">
                                                    <img src="#" alt="" class="tabul_container_item_image">
                                            </label>
                                        </div>
                                        <div class="col-12 col-sm-6 col-lg-4 image_box static_image">
                                            <label class="tabul_container_item">
                                                <input class="tabul_container_item_input" type="file" name="photo">
                                                <img src="#" alt="" class="tabul_container_item_image">
                                            </label>
                                        </div>
                                        <div class="col-12 col-sm-6 col-lg-4 add_box">
                                            <p class="add_box_item">+</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="galleryAdmin_modal_container_btn">Save</button>
                        </form>
                        <img src="{{ asset('images/admin/close.png') }}" alt=""
                             class="galleryAdmin_modal_container_closer">
                    </div>
                </div>

            </div>
        </section>
    </main>
@endsection

saskatoon/resources/views/admin/navigation.blade.php
<div class="settingAdmin_nav">
    <a href="{{ route('index') }}" class="settingAdmin_nav_link">
        <img src="{{ asset('images/admin/logo.svg') }}" alt="" class="settingAdmin_nav_link_image">
    </a>
    <div class="settingAdmin_list">
        <a href="{{ route('admin.testimonial.index') }}" class="settingAdmin_list_item @if (Route::currentRouteName() == 'admin.testimonial.index') current-page @endif">
            <img src="{{ asset('images/admin/testimonialsAdmin.png')}}" alt="" class="settingAdmin_list_item_icon">
            <p class="settingAdmin_list_item_text">Testimonials</p>
        </a>
        <a href="{{ route('admin.faq.index') }}" class="settingAdmin_list_item @if (Route::currentRouteName() == 'admin.faq.index') current-page @endif">
            <img src="{{ asset('images/admin/faqAdmin.png')}}" alt="" class="settingAdmin_list_item_icon">
            <p class="settingAdmin_list_item_text">FAQ</p>
        </a>
        <a href="{{ route('admin.gallery.show', 'residential') }}" class="settingAdmin_list_item
                @if (request()->path() == 'admin/gallery/residential') current-page @endif">
            <img src="{{ asset('images/admin/galleryAdmin.png')}}" alt="" class="settingAdmin_list_item_icon">
            <p class="settingAdmin_list_item_text">Gallery</p>
        </a>
        <a href="{{ route('admin.client.index') }}" class="settingAdmin_list_item
               @if (Route::currentRouteName() == 'admin.client.index') current-page @endif">
            <img src="{{ asset('images/admin/avatar.png')}}" alt="" class="settingAdmin_list_item_icon">
            <p class="settingAdmin_list_item_text">Clients</p>
        </a>
        <a href="{{ route('admin.setting') }}" class="settingAdmin_list_item @if (Route::currentRouteName() == 'admin.setting') current-page @endif">
            <img src="{{ asset('images/admin/settingsAdmin.png')}}" alt="" class="settingAdmin_list_item_icon">
            <p class="settingAdmin_list_item_text">Settings</p>
        </a>
    </div>

    <form class="exit_item_admin" action="{{ route('logout') }}" method="POST">
        @csrf
        <button>
            <img src="{{ asset('images/admin/exit.svg') }}" alt="" class="settingAdmin_list_item_icon">
            <p class="settingAdmin_list_item_text">Exit</p>
        </button>
    </form>
</div>

saskatoon/resources/views/admin/setting.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <main id="settingsAdmin">

        <section class="settingsAdmin_section">

            @include('admin.navigation')

            <div class="settingAdmin_block">
                <div class="settingAdmin_block_title">
                    <img src="{{ asset('images/admin/settingAdmin_title.png') }}" alt="" class="settingAdmin_block_title_icon">
                    <p class="settingAdmin_block_title_text">Settings</p>
                </div>

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (\Session::has('error'))
                    <div class="alert alert-danger">
                        <ul>
                            @foreach (\Session::get('error') as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (\Session::has('success'))
                    <div class="alert alert-success">
                        <ul>
                            @foreach (\Session::get('success') as $success)
                                <li>{{$success}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                <p class="settingAdmin_block_desc">Change Password</p>
                <form class="settingAdmin_form" action="{{route('admin.setting.update', $user)}}" method="post">
                    <div class="settingAdmin_form_row">
                        <div class="settingAdmin_form_item">
                            <p class="settingAdmin_form_item_desc">Old Password*</p>
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="password" name="current-password" class="settingAdmin_form_item_input">
                        </div>
                        <div class="settingAdmin_form_item">
                            <p class="settingAdmin_form_item_desc">New Password*</p>
                            <input type="password" name="password" class="settingAdmin_form_item_input">
                        </div>
                        <div class="settingAdmin_form_item">
                            <p class="settingAdmin_form_item_desc">Confirm Password*</p>
                            <input type="password" name="password_confirmation" class="settingAdmin_form_item_input">
                        </div>
                    </div>
                    <div class="settingAdmin_form_item">
                        <input type="submit" value="Save New Password" class="settingAdmin_form_item_input input_submit_btn">
                    </div>
                </form>

            </div>
        </section>
    </main>


@endsection